version: "3"
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/etc/letsencrypt:/etc/nginx/ssl
    depends_on:
      - backend

  backend:
    image: backend:latest
    ports:
      - "8081:8081"
