version: "3"
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx/nginx.conf/:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/nginx/ssl
      - ./dhparam:/etc/nginx/dhparam
    depends_on:
      - backend

  backend:
    image: backend:latest
    ports:
      - "8081:8081"
