version: '3'

services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt
      
  backend:
    image: backend:latest
    container_name: backend-blue
    ports:
      - '8081:8081'
