version: "3"
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/etc/nginx/nginx.conf:./Nginx/nginx.conf/
      - ~/etc/nginx/ssl:/etc/letsencrypt
      - ~/etc/nginx/dhparam:./dhparam
    depends_on:
      - backend

  backend:
    image: backend:latest
    ports:
      - "8081:8081"
