version: "3"
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/service-url.inc:/etc/nginx/service-url.inc
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - backend

  backend:
    image: backend:latest
    ports:
      - "8081:8081"
