version: '3'

services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/shopping-backend/Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/shopping-backend/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend

  backend:
    image: backend:latest
    container_name: backend-blue
    ports:
      - '8081:80'
      - '8081:443'