name: deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.DEV_HOST}}
          username: ${{secrets.DEV_USER}}
          key: ${{ secrets.DEV_KEY }}
          port: ${{ secrets.DEV_PORT }}
          script: |
            cd ./shopping-backend
            ./test.sh
              
          
        

      
