name: deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: EC2 Docker Run
        env:
            PRIVATE_KEY: ${{ secrets.DEV_KEY }}
            HOSTNAME: ${{secrets.DEV_HOST}}
            USER_NAME: ${{secrets.DEV_USER}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ec2-user/shopping-backend
              docker-compose -f docker-compose.yml down --rmi all
              docker build -t backend .
              docker-compose -f docker-compose.yml up -d 
              '
          
        

      
